name: 'Test'
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    environment: test

    permissions:
      # Required to checkout the code
      contents: read
      # Required to put a comment into the pull-request
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - name: 'Install Node'
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false
      - name: Install dependencies
        run: pnpm install

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - uses: supabase/setup-cli@v1
        name: Install Supabase CLI
        with:
          version: latest

      - name: Start Supabase local development setup
        run: supabase start

      - name: 'Run integration test'
        run: npx pnpm supabase:seed && vitest run --config ./vitest.integration.config.ts
